### ISSUE TITLE
Bug - RecyclerView

### ISSUE THREAD

**Issue by TurKurT656** [iammert/MaterialIntroView#8]
TnQ for this amazing lib.

i tried to show intro on items of a recyclerview with this code:
```
View introView = mRecyclerView.getChildAt(studentData.size()-1);

new MaterialIntroView.Builder(NewGradeActivity.this)
                                .setFocusGravity(FocusGravity.CENTER)
                                .setFocusType(Focus.MINIMUM)
                                ...
                                .setTarget(introView)
                                .show();
```
but there is a error:

`
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationInWindow(int[])' on a null object reference
                                                                       at co.mobiwise.materialintro.target.ViewTarget.getPoint(ViewTarget.java:22)
                                                                       at co.mobiwise.materialintro.shape.Circle.getFocusPoint(Circle.java:60)
                                                                       at co.mobiwise.materialintro.shape.Circle.<init>(Circle.java:40)
                                                                       at co.mobiwise.materialintro.view.MaterialIntroView$Builder.build(MaterialIntroView.java:688)
                                                                       at co.mobiwise.materialintro.view.MaterialIntroView$Builder.show(MaterialIntroView.java:698)
                                                                       at ir.uniquedev.okul.NewGradeActivity$5.onResponse(NewGradeActivity.java:274)
                                                                       at ir.uniquedev.okul.NewGradeActivity$5.onResponse(NewGradeActivity.java:247)
                                                                       at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:67)
                                                                       at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
                                                                       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                       at android.os.Looper.loop(Looper.java:194)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
`

**Comment by iammert** [comment]
Because you pass null View to material Intro View. Try to call MaterialView after adapter is set. This is tricky but it works. Try that.

```
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                new MaterialIntroView.Builder(NewGradeActivity.this)
                        .setFocusGravity(FocusGravity.CENTER)
                        .setFocusType(Focus.MINIMUM)
                        .setTarget(recyclerView.getChildAt(0))
                        .show();
            }
        },200);
```

**Comment by muratcanbur** [comment]
Hi @TurKurT656,

if you check the sample app, you can find RecyclerviewFragment that will guide you how to use MaterialIntroView with Recyclerview.
